DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  surname VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  is_owner BOOLEAN NOT NULL DEFAULT FALSE,
  password VARCHAR(255) NOT NULL
);
